/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pokedex;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author joao1
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    // Declarando objetos da tela de menu.
    private TelaInicial telaInicial;
    private TelaRegistro telaRegistro;
    private String iDTrainer;
    private TelaConfirmacao telaConfirmacao;
    
    public TelaMenu() {
        initComponents();
        // Iniciando os objetos de telas.
        telaInicial = new TelaInicial();
        telaRegistro = new TelaRegistro();
        telaConfirmacao = new TelaConfirmacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        lblTrainerCard = new javax.swing.JLabel();
        lblTelainicial = new javax.swing.JLabel();
        lblTelaregistro = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        btnTrainerCard = new javax.swing.JButton();
        btnTelaregistro = new javax.swing.JButton();
        btnTelaInicial1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 430));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 430));
        getContentPane().setLayout(null);

        lblTrainerCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spritespokemom/007.gif"))); // NOI18N
        lblTrainerCard.setText("jLabel1");
        lblTrainerCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTrainerCardMouseClicked(evt);
            }
        });
        getContentPane().add(lblTrainerCard);
        lblTrainerCard.setBounds(410, 250, 130, 100);

        lblTelainicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spritespokemom/004.gif"))); // NOI18N
        lblTelainicial.setText("jLabel1");
        lblTelainicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTelainicialMouseClicked(evt);
            }
        });
        getContentPane().add(lblTelainicial);
        lblTelainicial.setBounds(210, 250, 150, 100);

        lblTelaregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spritespokemom/001.gif"))); // NOI18N
        lblTelaregistro.setText("jLabel1");
        lblTelaregistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTelaregistroMouseClicked(evt);
            }
        });
        getContentPane().add(lblTelaregistro);
        lblTelaregistro.setBounds(-20, 260, 130, 90);

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spritespokemom/133.gif"))); // NOI18N
        lblSair.setText("jLabel1");
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
        });
        getContentPane().add(lblSair);
        lblSair.setBounds(400, 100, 140, 100);

        btnTrainerCard.setBackground(new java.awt.Color(33, 161, 212));
        btnTrainerCard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTrainerCard.setForeground(new java.awt.Color(7, 124, 168));
        btnTrainerCard.setText("TreinerCard");
        btnTrainerCard.setToolTipText("");
        btnTrainerCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrainerCardActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrainerCard);
        btnTrainerCard.setBounds(430, 330, 140, 40);

        btnTelaregistro.setBackground(new java.awt.Color(12, 198, 107));
        btnTelaregistro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTelaregistro.setForeground(new java.awt.Color(12, 149, 43));
        btnTelaregistro.setText("Telaregistro");
        btnTelaregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaregistroActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaregistro);
        btnTelaregistro.setBounds(10, 330, 140, 40);

        btnTelaInicial1.setBackground(new java.awt.Color(255, 122, 34));
        btnTelaInicial1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTelaInicial1.setForeground(new java.awt.Color(204, 102, 0));
        btnTelaInicial1.setText("TelaInicial");
        btnTelaInicial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicial1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTelaInicial1);
        btnTelaInicial1.setBounds(230, 330, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gifs/newFundo.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setRequestFocusEnabled(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 600, 410);
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrainerCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrainerCardActionPerformed
        // TODO add your handling code here:
        // Botão que vai deixar a tela Treiner Card visivel.
        this.telaConfirmacao.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTrainerCardActionPerformed

    private void btnTelaregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaregistroActionPerformed
        // TODO add your handling code here:
        // Botão que deixara a tela de registro visivel.
        this.telaRegistro.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTelaregistroActionPerformed

    private void btnTelaInicial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicial1ActionPerformed
        // TODO add your handling code here:
        // Botão que vai deixar a tela inicial visivel.
        this.telaInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTelaInicial1ActionPerformed

    private void lblTelaregistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTelaregistroMouseClicked
        // TODO add your handling code here:
        // Label que vai deixar a tela de registro visivel.
         this.telaRegistro.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblTelaregistroMouseClicked

    private void lblTelainicialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTelainicialMouseClicked
        // TODO add your handling code here:
        // label que vai deixar a tela inicial visivel.
        this.telaInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblTelainicialMouseClicked

    private void lblTrainerCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTrainerCardMouseClicked
        // TODO add your handling code here:
        // Label que vai deixar a tela Trainer Card visivel.
       this.telaConfirmacao.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblTrainerCardMouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        // TODO add your handling code here:
        // Label que vai encerrar o programa.
        System.exit(0);
    }//GEN-LAST:event_lblSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTelaInicial1;
    private javax.swing.JButton btnTelaregistro;
    private javax.swing.JButton btnTrainerCard;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblTelainicial;
    private javax.swing.JLabel lblTelaregistro;
    private javax.swing.JLabel lblTrainerCard;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the iDTrainer
     */
    public String getiDTrainer() {
        return iDTrainer;
    }

    /**
     * @param iDTrainer the iDTrainer to set
     */
    public void setiDTrainer(String iDTrainer) {
        this.iDTrainer = iDTrainer;
    }
}
